apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: Auth
  description: Retrieve bank account information to set up electronic funds transfers, such as ACH payments in the US, EFT payments in Canada, BACS payments in the UK, and IBAN / SIC payments in the EU.
  annotations:
    github.com/project-slug: ${{values.destination.owner + "/" + values.destination.repo}}
    backstage.io/techdocs-ref: dir:.
  tags:
    - ach
    - authentication
    - finance
spec:
  type: openapi
  lifecycle: production
  owner: payments
  definition:
    $text: ./auth-payments.yaml
  visibility: public