site_name: Auth API Documentation
site_description: Documentation for the Auth API service

theme:
  name: material

nav:
  - Home: index.md
  - API Overview: 
    - Authentication: overview/authentication.md
    - Use Cases: overview/use-cases.md
  - Changelog: changelog.md

plugins:
  - techdocs-core